### ISSUE TITLE
Media query 

### ISSUE THREAD

**Issue by sheri-thomson** [sheri-thomson/responsive-image-section#1]
@hellachella

At 608px I can't get my image to jump up beside the content.

I also don't know where vertical-align: middle; text-align: centre; and text-align: left are supposed to go...

**Comment by hellachella** [comment]
Vertical align puts content in the middle of your div rather than aligning it to the top or bottom. 

Text align is like text align in a word processor. Do you want it left justified/centered/right? You apply it to text blocks.

https://learn-the-web.algonquindesign.ca/topics/css-layout-cheat-sheet/#centering-elements

**Comment by sheri-thomson** [comment]
@hellachella 
Okay great thank you :)
